<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Donation Simulator</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="container">
    <div class="total-donation">
      <p>Total Donation Amount: $<span id="total-amount">0.00</span></p>
    </div>
    <h1>Donation Simulator</h1>
    <div class="form">
      <label for="username">Username:</label>
      <input type="text" id="username" placeholder="Enter username">
      <label for="amount">Enter Donation Amount:</label>
      <input type="number" id="amount" min="0" step="0.01" placeholder="Enter amount">
      <label for="message">Message:</label>
      <input type="text" id="message" placeholder="Enter message">
      <button onclick="makeDonation()">Donate</button>
    </div>
    <div class="donation-history">
      <h2>Donation History</h2>
      <div id="history-container"></div>
    </div>
    <button id="restart-btn" onclick="resetDonations()">Restart</button>
  </div>
  <script src="script.js"></script>
</body>
</html>
